### ISSUE TITLE
Batch job issue on 4 GPUs

### ISSUE THREAD

**Issue by AnandSingh-0619** [AnandSingh-0619/home-robot#7]
I am facing CUDA out of memory error while trying to run batch job on 4 GPUS. However there is no error on running the same job on single GPU. The weights of the Yolo and SAM model are frozen.
Agent Number of parameters in original ovmm code: 9485655
Agent Number of parameters in yolo ovmm code: 9496503

Attached below are log files for original and yolo config running a batch job on 4 GPUs.
[home_robo-ver-846357yolo4GPU.log](https://github.com/AnandSingh-0619/home-robot/files/14825075/home_robo-ver-846357yolo4GPU.log)
[original](https://drive.google.com/file/d/18la08PM9pPcia4CySucXpU8a6xL5UU9s/view?usp=sharing)

**Comment by yusufali98** [comment]
Okay, I can access only the yolo4GPU log file and the other link does not lead me to any log file so can you please fix ? Also, it might be good to run the multi-GPU batch job with `HABITAT_ENV_DEBUG=1` so that you can get more informed error log.

Few questions:

1. What is the memory usage during training when you are running a single GPU batch job ? Also, I am assuming the single GPU batch job has same number of parameters (total and trainable) ?
2. Can you please also share the config files for yolo/original policy as I want check few other details ?
3. Can you also print the **number of trainable parameters** as well as is done [here](https://github.com/facebookresearch/habitat-lab/blob/main/habitat-baselines/habitat_baselines/rl/ppo/ppo.py#L113-L116) ?
4. Why are the number of parameters for the original ovmm policy and yolo ovmm policy very similar ? I would expect **larger number of parameters in yolo policy** because the detector has atleast 13 mil parameters ([Paper Table 2](https://arxiv.org/pdf/2401.17270.pdf)) and mobileSAM has around 6 mil parameters. So yolo policy should have atleast 20 mil extra parameters but since we freeze the detector/segmentor weigths, the **number of trainable parameters** should be exactly same as the original ovmm policy (to the last digit)

**Comment by AnandSingh-0619** [comment]
1. Single GPU yolo batch job:
agent number of parameters: 9496503
[home_robo-ver-846571.log](https://github.com/AnandSingh-0619/home-robot/files/14827579/home_robo-ver-846571.log)
Yes total and trainable are same.
2. [YOLO](https://github.com/AnandSingh-0619/home-robot/blob/anand_dev/projects/habitat_uncertainity/config/yolo_rl_skill.yaml)
[Original](https://github.com/facebookresearch/habitat-lab/blob/b727ca9f7123101aaedb737ca9ccc1b153525dd9/habitat-baselines/habitat_baselines/config/ovmm/rl_skill.yaml)
3. Added in log above
4. Agent Number of parameters in original ovmm code: 9485655
Agent Number of parameters in yolo ovmm code: 9496503
these are the numbers I am getting

**Comment by yusufali98** [comment]
1. I meant that you need to go and manually check the memory usage of single batch job by ssh-ing into the compute node and checking how much VRAM is your batch job consuming when you run training with single GPU. Please run the single GPU batch job and attach a screenshot of the output of `nvidia-smi` on the compute node with your process marked so that we can see what is the GPU VRAM usage in single GPU job. Also I still dont see **"Number of params to train: "** explicitly printed anywhere in the logs you shared so how are you claiming that the total and trainable are the same ? Please add the code to print total number of trainable parameters as I mentioned in earlier comment (like [this](https://github.com/facebookresearch/habitat-lab/blob/main/habitat-baselines/habitat_baselines/rl/ppo/ppo.py#L113-L116))
2. Please remove all the unnecessary commented things from your yolo config. Also can you clarify why are we using this /`habitat/simulator/sim_sensors@habitat.simulator.agents.main_agent.sim_sensors.head_rgb_sensor: head_rgb_sensor` ?
3. The logs still **do not print** out the number of trainable parameters. This is different from the total number of parameters in the policy/agent and you need to check comment 1. for printing total trainable parameters
4. This is not expected behavior as per my earlier comment regarding number of parameters. You need to dig deeper into why this is happening. You should individually print out the number of parameters in the detector and segmentor as well to see why the yolo policy does not have significantly more parameters. I would strongly suggest you to first figure out why this is happening before trying any other random changes. 
5. I see you have no print/log statements in your policy code at all. Please add print statements in various parts (encoder/policynet/etc) of the policy to verify everything is being loaded as expected. Also I would suggest to remove unwanted things from the policy code to ensure it doesnt get used accidentally such as [this](https://github.com/AnandSingh-0619/home-robot/blob/anand_dev/projects/habitat_uncertainity/models/yoloPointNavResNetPolicy.py#L351-L463) and [this](https://github.com/AnandSingh-0619/home-robot/blob/anand_dev/projects/habitat_uncertainity/models/yoloPointNavResNetPolicy.py#L690-L704). Also, why is `yoloResNetEncoder` used [here](https://github.com/AnandSingh-0619/home-robot/blob/anand_dev/projects/habitat_uncertainity/models/yoloPointNavResNetPolicy.py#L653) ? You should be careful with using heavy classes in the custom code as it might be loading the yoloResNetEncoder twice without you knowing (although unlikely right now)

**Comment by AnandSingh-0619** [comment]
1. Single GPU
![image](https://github.com/AnandSingh-0619/home-robot/assets/69452312/981ebee8-86d6-455e-8795-0524564074fb)
Multiple GPUs batch job (GPUs: 0,1,4,5)
![image](https://github.com/AnandSingh-0619/home-robot/assets/69452312/3d858a0f-f447-41d2-92b4-2336d8db775a)

Here is a log file where total and trainable number of parameters are printed as required
[home_robo-ver-847179.log](https://github.com/AnandSingh-0619/home-robot/files/14842139/home_robo-ver-847179.log)

2. `habitat/simulator/sim_sensors@habitat.simulator.agents.main_agent.sim_sensors.head_rgb_sensor: head_rgb_sensor`
I need this line to include the head_rgb sensor for main agent in simulator before calling [this](https://github.com/AnandSingh-0619/home-robot/blob/anand_dev/projects/habitat_uncertainity/config/yolo_rl_skill.yaml#L47C1-L55C35).

3. Printed in log file of point 1.
4. Not figured out yet
5. Working on it.

**Comment by yusufali98** [comment]
Okay thanks for the response:

1. So this is with 4 environments right as per the config you shared earlier ? Also are these screenshots for yolo policy or original policy ? Please share results for both variants with proper labels so that we can compare and understand what is going on. If this is for yolo policy, it is still very strange as I would not expect such high GPU VRAM usage with only 4 environments. We need to be able to run stuff with **atleast 16 (or 32 ideally)** environments. Your FPS results will also be significantly affected by the number of environments you use so we really need to fix this before you try to generate any meaningful results
2. Okay got it
3. Yeah, this is again not expected output and we need to understand why this is happening. Please print out the number of parameters for the detector/segmentor individually as well to further debug what is going on

**Comment by AnandSingh-0619** [comment]
The screenshots in the previous comment are for yolo policy with 
habitat_baselines.num_environments=10

**Comment by yusufali98** [comment]
So what is the VRAM usage in case of original OVMM policy with 10 num_environments with 4 GPUs ? We need to understand by how much %age is the VRAM usage shooting up **just by adding the frozen detector/segmentor** and keeping all other experimental configs exactly the same

**Comment by yusufali98** [comment]
Btw, I just noticed that you are hardcoding the GPU device id to 0 in all these statements which can be very problematic ([this](https://github.com/AnandSingh-0619/home-robot/blob/anand_dev/projects/habitat_uncertainity/models/yoloPointNavResNetPolicy.py#L307), [this](https://github.com/AnandSingh-0619/home-robot/blob/anand_dev/projects/habitat_uncertainity/models/yoloPointNavResNetPolicy.py#L313) and [this](https://github.com/AnandSingh-0619/home-robot/blob/anand_dev/projects/habitat_uncertainity/models/yoloPointNavResNetPolicy.py#L321)) during multi-GPU training. 

During multi-GPU training, each yolo policy class will be on a different cuda device which can have arbitrary device ID so you cant simply hardcode the device ID to a specific value such as 0. I think this could be explain why you were seeing issues during multi-GPU training because in single-GPU training the device is always 0. Interestingly, you do use `torch.cuda.current_device()` in some parts of the code within that function so I am not sure why you hardcode the ID to 0 in some cases and not in others. 

Also why do you keep converting all the tensors to numpy arrays repeatedly ([this](https://github.com/AnandSingh-0619/home-robot/blob/anand_dev/projects/habitat_uncertainity/models/yoloPointNavResNetPolicy.py#L289-L292)) ? You can achieve all those operations on torch tensors so the conversion is unnecessary honestly. Every cpu -> gpu -> cpu transfer takes time and will affect FPS (although negligibly, but it definitely will)

**Comment by AnandSingh-0619** [comment]
Figured out the CUDA out-of-memory issue but was unable to resolve it. 
Issue: Irregular shape of head_rgb sensor. Normally the shape of the RGB sensor is num_environments*height(160)*width(120)*3. But during training, in some iteration the size becomes (1024/2048) * 160 *1 20 *3. Since this batch size is much larger, the yolo model takes lots of vRAM to process it and gives out of memory issue.
Quick fix: Whenever batch size is greater than num_envs, truncate the tensor to match the batch size.
[Link to code](https://github.com/AnandSingh-0619/home-robot/blob/65f5b52dc7b8ba7cadbfe34f272cf873f2b25e00/projects/habitat_uncertainity/utils/YOLO_pred.py#L143C9-L146C35)
Attached below is the log file. 
![image](https://github.com/AnandSingh-0619/home-robot/assets/69452312/b69705f7-cf07-4817-a280-b5e8b708452e)

**Comment by yusufali98** [comment]
Hmmm, I have never encountered such an error before in Habitat and it is very abnormal. Few questions:

1. What is the exact sensor that gives this issue ? Can you provide link to source code of the sensor in habitat ? Is there anything that you added in the code flow of that sensor ?
2. When you encounter this issue with the `head_rgb` sensor, are the other sensors in the observations space also returning tensor of dimension `(1024/2048) x .... x .....` or is it only the `head_rgb` sensor that has this issue ?

**Comment by AnandSingh-0619** [comment]
1. head_rgb_sensor is the sensor name. [Link](https://github.com/facebookresearch/habitat-lab/blob/b727ca9f7123101aaedb737ca9ccc1b153525dd9/habitat-lab/habitat/config/default_structured_configs.py#L1618C1-L1622C22). No I've not added anything to this code. I have just added it to my main [config file](https://github.com/AnandSingh-0619/home-robot/blob/anand_dev/projects/habitat_uncertainity/config/yolo_rl_skill.yaml#L6C6-L6C116).

2. All other sensor like head_depth_sensor have the same tensor dimension`(1024/2048) x .... x .....`

**Comment by yusufali98** [comment]
I think the issue here was that you weren't caching the pretrained visual features which you resolved right ?

**Comment by AnandSingh-0619** [comment]
yes this issue was resolved.
